###GET HOMe page /
GET http://localhost:8081/

###POST to register a user
POST  http://localhost:8081/auth/register
Content-Type: application/json

{
    "university_id":"f20220226",
    "username":"SriRam",
    "password":"123123"
}

###POST to login a user
POST  http://localhost:8081/auth/login
Content-Type: application/json

{
    "id":"f20220226",
    "password":"123123"
}

###New test case of user signed up
POST  http://localhost:8081/auth/login
Content-Type: application/json

{
    "username":"drizzgesh@gmail.com",
    "password":"j318nmd1398eu"
}

//TODOs:

###Get the todos of the user- can't unless give the auth string in the header of this body
GET  http://localhost:8081/todos/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk



###POSt the new data
POST  http://localhost:8081/todos/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk
Content-Type: application/json

{
    "task":"Finish Coding the projects"
}

###UPDATE with put the new data
PUT  http://localhost:8081/todos/4/taskUpdate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk
Content-Type: application/json

{
    "task":"Finish Coding the project 4",
    "completed":1
}


###Update the button with done // the rest of the params added extra in the request payload is ignored by the backend
PUT  http://localhost:8081/todos/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk
Content-Type: application/json

{
    "task": "Can change this line",
    "completed":1
}


###Delete the task
DELETE  http://localhost:8081/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk


