###GET HOMe page /
GET http://localhost:8081/

###POST to register a user
POST  http://localhost:8081/auth/register
Content-Type: application/json

{
    "university_id":"f20220226",
    "username":"SriRam",
    "password":"123123"
}

###POST to login a user
POST  http://localhost:8081/auth/login
Content-Type: application/json

{
    "id":"f20220226",
    "password":"123123"
}


//Events :

###Get the events of the user- can't unless give the auth string in the header of this body
GET  http://localhost:8081/events/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo



###POST a new event
POST  http://localhost:8081/events/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo
Content-Type: application/json

{
    "title": "New event",
    "description": "Description of event1",
    "date": "2023-09-15",
    "fromTime": "14:30:00",
    "ToTime": "16:30:00",
    "eventVenue": "IN our heads",
    "banner_image": null
}

###Register user to event
POST  http://localhost:8081/events/user-event/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo
Content-Type: application/json

{
    "user_id":"f20220226",
    "event_id":"4"
}

###Verify user to event - MOD ONLY
PUT  http://localhost:8081/events/user-event/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo
Content-Type: application/json

{
    "user_id":"f20220226",
    "event_id":"4",
    "isParticipated":1
}

###Get All registered users for event

//MOD ONLY:
GET  http://localhost:8081/events/user-event?query=usersForEvents&event_id=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo

###Get All registered events for user
GET  http://localhost:8081/events/user-event?query=eventsForUser&user_id=f20220226
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo

###Get All registered events for user in which he Participated
GET  http://localhost:8081/events/user-event?query=eventsForUserParticipated&user_id=f20220226
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlhdCI6MTc0NzkzNjg3MywiZXhwIjoxNzQ4MDIzMjczfQ.V0Hj9jSDgvt6FiyqoHy6WL-UXTg8NNK5eNYhU3nfDQo





###UPDATE with put the new data
PUT  http://localhost:8081/events/4/taskUpdate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDc5MjA2NTYsImV4cCI6MTc0ODAwNzA1Nn0.1BmhW4vRgq7BEDxnDVAf0in2dWxakudtRK1qf_tOPmE
Content-Type: application/json

{
    "task":"Finish Coding the project 4",
    "completed":1
}


###Update the button with done // the rest of the params added extra in the request payload is ignored by the backend
PUT  http://localhost:8081/events/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk
Content-Type: application/json

{
    "task": "Can change this line",
    "completed":1
}


###Delete the task
DELETE  http://localhost:8081/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpZCI6MSwiaWF0IjoxNzQ3NzcxMTA2LCJleHAiOjE3NDc4NjgzMDZ9.ec9sxYk5W8UH8iB-KlcD0FsqhEBtCH2_dTI_34bB-rk


