GET http://localhost:8991/


###POST to register a user
POST http://localhost:8991/send
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ4MDg0MDM0LCJleHAiOjE3NDgxODEyMzR9.SvuZaBEdfagR1ChNSbW6nxSBGgaAcFhbnS9u64CbpRc

{
  "title": "Notification",
  "message": "Notifs changed into updates.",
  "time": "2025-05-24T15:00:00Z",
  "isRead": false
}