import express from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import prisma from '../prismaClient.js'
import Redis from 'ioredis';
import nodemailer from 'nodemailer';
import crypto from 'crypto';
const router=express.Router();

const client = new Redis(process.env.REDIS_URL);
//Change this line if we want to expand to different campuses
const campus_id="hyderabad.bits-pilani.ac.in";
function generateOTP(){
    return crypto.randomInt(100000,999999);
}

const transporter = nodemailer.createTransport({
    host: "smtp-relay.brevo.com",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.BREVO_LOGIN,
      pass: process.env.BREVO_PASSWORD,
    },
});

//we encrypt the password and save the encryptes password
// and save this in the db, if equal then we're safe

router.post('/login',async(req,res)=>{
    let {id,password}=req.body;

    //check the username and password which is hashed
    //with db and log them into the app.
    console.log(`${id} is the id of the user  recieved`)
    try{
        const user = await prisma.user.findUnique({
            where: {
                university_id: id
            }
        });
        console.log(user);
        
        //Guard to check if user in db
        if (!user) { 
            console.log('User Not found!');
            return res.status(404).send({"message": 'User Not Found!'});
        }
        console.log('User is present in db')

        //Guard to check if user's db stored password has correct passwd
        const passwordIsValid = bcrypt.compareSync(password, user.password);
        
        if (!passwordIsValid) {
            console.log('Invalid password! Message sent to user');
            return res.status(401).send({"message": "Invalid password!"})
        }

        console.log('User entered valid password')
        //user is authenticated, we can move in...
        const token = jwt.sign(
            { 
                id: id,  // Add the user ID to the token
                isAdmin: user.isAdmin  // Now directly a boolean with Prisma
            }, 
            process.env.JWT_SECRET, 
            { expiresIn: '50h' }
        );
        
        res.json({
            success: true,
            token: token,
            username: user.username,
            user_id: user.university_id,
            isAdmin: user.isAdmin, // Already boolean in Prisma, no conversion needed
            isVolunteer: user.isVolunteer,
            isWishVolunteer: user.isWishVolunteer,
            message: 'Login successful'
        });
        //user has new token
    }catch(err){
        console.log(err);
        res.sendStatus(503);
    }
});

/*
Addition to /forgotPassword
The forgot password should send back a mail to the user
The user should then be able to change password via the link given by the mail...
The link generated by the change password should be valid for 10 minutes 


Forgot password flow:
-The user clicks on forgot password, enters their user id(just new frontend page)
-on entering ID and clicking on forgot password button
-we send them an email with the /forgotPassword POST
-The endpoint sends the user an email with the hash value and stores token on redis.
-the frontend has the otp and the password to be entered twice into it.
-on clicking the reset password on this page calls the /resetPassword endpoint.
-The reset password authenticates the otp with the help of redis
-Then stores the new password into the db.
-Frontend goes back to login page
*/


//The user forgets the password
router.post('/forgotPassword',async(req,res)=>{
    //ask the user to send in their id and paste the otp
    const {university_id}= req.body;
    //display a message that says that the passwd would be confirmed only with the otp confirmation on the frontend
    try{
        const hashedOTP=generateOTP();
        //push to Redis...
        client.setex(`forgotPassword@${university_id}`,605,JSON.stringify({university_id,hashedOTP}));
        // Send email with HTML formatting
        let info = await transporter.sendMail({
            from: process.env.NSS_MAIL,
            to: `${university_id}@${campus_id}`,
            subject: "NSS - Your OTP Code",
            text: `To authenticate, please use the following One Time Password (OTP): ${specialHash}. This OTP will be valid for 10 minutes.`,
            html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #333;">NSS App Authentication</h1>
                </div>
                <p>Hello ${username},</p>
                <p>To authenticate your account, please use the following One Time Password:</p>
                <div style="background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 24px; letter-spacing: 5px; margin: 20px 0; border-radius: 4px;">
                <strong>${hashedOTP}</strong>
                </div>
                <p>This OTP will be valid for <strong>10 minutes</strong>.</p>
                <div style="margin: 20px 0; padding: 15px; background-color: #fff8e1; border-left: 4px solid #ffc107; font-size: 14px;">
                <p style="margin: 0;"><strong>Security Notice:</strong> Do not share this OTP with anyone. NSS will never ask for this code via phone or email.</p>
                </div>
                <p>If you didn't request this code, you can safely ignore this email.</p>
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="color: #777; font-size: 12px; text-align: center;">Thank you for registering with NSS.</p>
            </div>
            `
        });

        console.log(`Message sent:${info.messageId}`);
        res.status(200).json({"message":"OTP message sent"});
    }catch(err){
        console.log(err);
        console.log("Unable to send OTP details for forgotten password");
        return res.status(501).json({"message":"Unable to send OTP details to user account"});
    }

});



//The user forgets the password
router.post('/resetPassword',async(req,res)=>{
    const {university_id,otpValue,password}=req.body;
    //ask the user to send in their id and paste the otp
    //display a message that says that the passwd would be confirmed only with the otp confirmation
    try{
        //validate the otpValue
        const passwordResetSession=await client.get(`forgotPassword@${university_id}`);

        if(passwordResetSession==null){
            console.log("Unable to retrieve from Redis");
            return res.status(401).json({"Bad Gateway":"Token Time Expired"});
        }
        
        const {hashedOTP}=JSON.parse(passwordResetSession);
        
        if(otpValue!=hashedOTP){
            console.log("OTP verification failed");
            return res.status(401).json({"message":"Incorrect OTP"});
        }
        
        //change the db
        const hashedPassword=bcrypt.hashSync(password,8);
        //we store this hashedPassword and replace the old password...

        await prisma.user.update({
            where:{
                university_id:university_id
            },
            data:{
                password:hashedPassword
            }
        })

        res.status(200).json({"message":"Updated Password"});
    }
    catch(err){
        console.log(err);
        console.log(`Unable to reset password for ${university_id}`);
        return res.status(501).send("Unable to reset Password");
    }
});

//In short the new changes for sign in:
/*
POST /register      → Full registration + first OTP
POST /resendOTP     → Just regenerate & send OTP  
POST /verifyUser    → Validate OTP & create user
*/

router.post('/register',async(req,res)=>{
    // recieve data from front end and push to redis db
    const {university_id,username,password} =req.body;
    try{
        const hashedPassword=bcrypt.hashSync(password,8);
        console.log(`${username} is trying to register`);
        //check if user already in db, otherwise proceed
        const userExists=await prisma.user.findUnique({
            where:{
                university_id:university_id
            }
        });

        if(userExists){
            console.log("User Already exists, user should skip registration");
            return res.status(400).json({"message":"User has already registered."});
        }
        
        //create special  6 digit hash non repeating within 10 minutes...
        let specialHash=generateOTP();
        
        //set up hash in redis 
        client.setex(`registrationFor${university_id}`,605,JSON.stringify({university_id,username,hashedPassword,specialHash}));

        
        // send email including hash to the user 
        let info = await transporter.sendMail({
            from: process.env.NSS_MAIL,
            to: `${university_id}@${campus_id}`,
            subject: "NSS - Your OTP Code",
            text: `To authenticate, please use the following One Time Password (OTP): ${specialHash}. This OTP will be valid for 10 minutes.`,
            html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #333;">NSS App Authentication</h1>
                </div>
                <p>Hello ${username},</p>
                <p>To authenticate your account, please use the following One Time Password:</p>
                <div style="background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 24px; letter-spacing: 5px; margin: 20px 0; border-radius: 4px;">
                <strong>${specialHash}</strong>
                </div>
                <p>This OTP will be valid for <strong>10 minutes</strong>.</p>
                <div style="margin: 20px 0; padding: 15px; background-color: #fff8e1; border-left: 4px solid #ffc107; font-size: 14px;">
                <p style="margin: 0;"><strong>Security Notice:</strong> Do not share this OTP with anyone. NSS will never ask for this code via phone or email.</p>
                </div>
                <p>If you didn't request this code, you can safely ignore this email.</p>
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="color: #777; font-size: 12px; text-align: center;">Thank you for registering with NSS.</p>
            </div>
            `
        });

        console.log(`Message sent:${info.messageId}`);
        res.json({"message":"OTP message sent"});

    }catch(err){
        console.log(err);
        console.log("Unable to create OTP for user");
        res.status(501).json({"message":"Unable to register user"});
    }
});


router.post('/resendOTP',async(req,res)=>{
    //OTP is resent to email service
    const {university_id}=req.body;
    try{
        //we check in redis if there is a relevant key with the ID
        const isUserAttemptedToRegister=await client.get(`registrationFor${university_id}`)
        
        if(isUserAttemptedToRegister==null){
            console.log("Bad Request");
            return res.status(400).json({"message":"Time Expired.Please try registering again"});
        }
        //get the value of username, hashedpassword from the redis
        const {username,hashedPassword}=JSON.parse(isUserAttemptedToRegister);
        //send the mail again with the help of the transporter, updating the value of the redis key
        let specialHash=generateOTP();
        
        //reset up the hash in redis 
        client.setex(`registrationFor${university_id}`,605,JSON.stringify({university_id,username,hashedPassword,specialHash}));
        
        

        // Send email with HTML formatting
        let info = await transporter.sendMail({
            from: process.env.NSS_MAIL,
            to: `${university_id}@${campus_id}`,
            subject: "NSS - Your OTP Code",
            text: `To authenticate, please use the following One Time Password (OTP): ${specialHash}. This OTP will be valid for 10 minutes.`,
            html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #333;">NSS App Authentication</h1>
                </div>
                <p>Hello ${username},</p>
                <p>To authenticate your account, please use the following One Time Password:</p>
                <div style="background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 24px; letter-spacing: 5px; margin: 20px 0; border-radius: 4px;">
                <strong>${specialHash}</strong>
                </div>
                <p>This OTP will be valid for <strong>10 minutes</strong>.</p>
                <div style="margin: 20px 0; padding: 15px; background-color: #fff8e1; border-left: 4px solid #ffc107; font-size: 14px;">
                <p style="margin: 0;"><strong>Security Notice:</strong> Do not share this OTP with anyone. NSS will never ask for this code via phone or email.</p>
                </div>
                <p>If you didn't request this code, you can safely ignore this email.</p>
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="color: #777; font-size: 12px; text-align: center;">Thank you for registering with NSS.</p>
            </div>
            `
        });

        console.log(`Message sent:${info.messageId}`);
        res.json({"message":"OTP message sent"});

    }catch(err){
        console.log(err);
        res.status(501).json({"message":"Unable to resend OTP. Please try again"});
    }
});


router.post('/verifyUser',async(req,res)=>{
    //we verify the user with the OTP they respond with...
    const {university_id,otpValue}=req.body;
    try{
        //check with redis if user exists and the values match
        const hasUserRegistered=await client.get(`registrationFor${university_id}`);
        
        if(hasUserRegistered==null){
            console.log("User isn't available on the redis server. Probably time expired");
            return res.status(401).json({"message":"Bad Gateway: OTP Time Expired"});
        }
        //if they dont match return invalid OTP
        const {username,hashedPassword,specialHash}=JSON.parse(hasUserRegistered);
        

        if(specialHash!=otpValue && uni_id!=university_id){
            console.log("Invalid OTP");
            return res.status(401).json({"message":"Invalid OTP"});
        }
        console.log("Verified User, Creating user");
        //insert user into db
        try {
            const result = await prisma.user.create({
                data: {
                    university_id,
                    username,
                    password: hashedPassword,
                    points: 0
                }
            });
            console.log('User Inserted into database');

            // Since university_id is the primary key in your schema, use it in the token
            const token = jwt.sign({id: result.university_id}, process.env.JWT_SECRET, {expiresIn:'24h'})

            //the token is saved locally for the user...
            res.json({token});//sending back the token to the user
            console.log('Token sent to user')


        } catch(err){
            console.log(err.message);
            console.log('Error registering user into database! Possibly user is already registered');
            
            res.sendStatus(503);
        }
    }catch(err){
        console.log(err);
        console.log("Unable to verify user");
        res.status(403).json({"message":"Unable to verify user with given credentials"});
    }
});


router.post('/register', async (req,res)=>{
    const {university_id,username,password,isAdmin}=req.body;
    console.log(`${university_id} is the id with ${username} as the username and the password is ${password}`);
    const hashedPassword=bcrypt.hashSync(password,8);
    console.log(`${hashedPassword} is the hashed password`);
    
    //save user and hashedPassword to db
    try {
        //db.prepare us to inject values into the sql query
        const result = await prisma.user.create({
            data: {
                university_id,
                username,
                password: hashedPassword,
                points: 0
            }
        });
        console.log('User Inserted into database');

        // Since university_id is the primary key in your schema, use it in the token
        const token = jwt.sign({id: result.university_id}, process.env.JWT_SECRET, {expiresIn:'24h'})

        //the token is saved locally for the user...
        res.json({token});//sending back the token to the user
        console.log('Token sent to user')


    } catch(err){
        console.log(err.message);
        console.log('Error registering user into database! Possibly user is already registered');
        
        res.sendStatus(503);
    }
    
});

export default router;



//New changes to entail with including the node mail server
/*
changes in /register:
The register should send a mail from the NSS account.
Only when the user confirms from their mail ID do we confirm their account
Then we add the mail ID to the database.



Problems with changing the db=>{
    -changing the rest of the APIs throughout the server
    -Shouldn't be done in case of lack of time - my case
}

Flow for sign up:
sign in the local app=>{
-email sent to the user(we dont need to take input of user email)
-This would prevent the fraud of all those acting to have a certain ID
-The email requires the user to confirm the sign up into the NSS app
-
}
*/