PUT http://localhost:8081/maintenance/createAdmin
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzQ4NDMyMzE3LCJleHAiOjE3NDg2MTIzMTd9.Csf0Vc0cQ9FBgsGtzgb-k5DLxfgj4i8IqhtsXKyk-Eo
Content-Type: application/json

{
  "university_id": "f20220226"
}

### Get all the users - ADMIN ONLY
GET http://localhost:8081/maintenance/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4MzM4NDcxLCJleHAiOjE3NDg0MzU2NzF9.MApI6lMLy0PwFx4XN5ELlvIqmNt-mi9ommBfRRb8QM4
### Get all the volunteers - ADMIN ONLY
GET http://localhost:8081/maintenance/volunteers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4MzM4NDcxLCJleHAiOjE3NDg0MzU2NzF9.MApI6lMLy0PwFx4XN5ELlvIqmNt-mi9ommBfRRb8QM4
### Register a new user
POST  http://localhost:8081/auth/register
Content-Type: application/json

{
    "university_id":"f20220210",
    "username":"SriRamhmm",
    "password":"123123"
}

###DEBUG: Check user_event table contents
GET http://localhost:8081/maintenance/user-events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4MTIzNzk4LCJleHAiOjE3NDgyMjA5OTh9.5M_YjNGlx_o0eQcwQ9rpxx2CNaH2nh0xpnyKN-ac0cM

###DEBUG: Register user to event again to test
POST  http://localhost:8081/events/user-event/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyMDIyMDIyNiIsImlzQWRtaW4iOjAsImlhdCI6MTc0ODIwNTkwNCwiZXhwIjoxNzQ4Mzg1OTA0fQ.iJFkIQRvi564P67aXyX6YwlTplaFIp_hoVihI83LkhE
Content-Type: application/json

{
    "user_id":"f20220226",
    "event_id":"4"
}

###Delete the user from db
DELETE http://localhost:8081/maintenance/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzUwMzE4MzEyLCJleHAiOjE3NTA0OTgzMTJ9.1XpXkPZXM80PvCLPVt4XkBGRUawdngDGLGWz3b6AKx8
Content-Type: application/json

{
  "university_id": "f20220226"
}


###GET ALl users
GET http://localhost:8081/maintenance/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzUwMzE4MzEyLCJleHAiOjE3NTA0OTgzMTJ9.1XpXkPZXM80PvCLPVt4XkBGRUawdngDGLGWz3b6AKx8

###GET ALl volunteers
GET http://localhost:8081/maintenance/volunteers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzUwMzE4MzEyLCJleHAiOjE3NTA0OTgzMTJ9.1XpXkPZXM80PvCLPVt4XkBGRUawdngDGLGWz3b6AKx8

### user wish a volunteer;
PUT http://localhost:8081/maintenance/wishVolunteer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzQ4NDMyMzE3LCJleHAiOjE3NDg2MTIzMTd9.Csf0Vc0cQ9FBgsGtzgb-k5DLxfgj4i8IqhtsXKyk-Eo
Content-Type: application/json

{
  "university_id":"f20220226"
}

### remove a volunteer;
PUT http://localhost:8081/maintenance/removeVolunteer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzQ4NDk4NDc0LCJleHAiOjE3NDg2Nzg0NzR9.sOxWUD-qW0KQvbx4ia5zBVAYFdn6Ma3rDZEQKhUpEGg
Content-Type: application/json

{
  "university_id":"f20220226"
}
###Make user a volunteer;
PUT http://localhost:8081/maintenance/makeVolunteer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzQ4NDk4NDc0LCJleHAiOjE3NDg2Nzg0NzR9.sOxWUD-qW0KQvbx4ia5zBVAYFdn6Ma3rDZEQKhUpEGg
Content-Type: application/json

{
  "university_id":"f20220226"
}